"""added role

Revision ID: 264e0eacc9c7
Revises: 7b5e00a02643
Create Date: 2026-06-22 11:47:53.278728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '264e0eacc9c7'
down_revision = '7b5e00a02643'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
